[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
    "tensorflow==2.16.2",
    "tensorflow-metal==1.1.0",
    "types-tensorflow>=2.18.0.20260408",
]

[project.scripts]
ms1 = "src.cli.ms1:main"

[tool.setuptools]
packages = [
    "src",
    "src.cli",
    "src.common",
    "src.ms1",
    "src.ms1.cleaning",
    "src.ms1.normalization",
    "src.ms1.spelling",
    "src.ms1.ingest",
    "src.ms2",
    "src.ms2.data",
    "src.ms2.models",
    "src.ms2.models.rnn",
    "src.ms2.models.rnn.encoder",
    "src.ms2.models.rnn.decoder",
    "src.ms2.util",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.5",
]
