[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
ms1 = "src.cli.ms1:main"

[tool.setuptools]
packages = [
    "src",
    "src.cli",
    "src.common",
    "src.ms1",
    "src.ms1.cleaning",
    "src.ms1.normalization",
    "src.ms1.spelling",
    "src.ms1.ingest",
    "src.ms2",
    "src.ms2.analysis",
    "src.ms2.data",
    "src.ms2.inference",
    "src.ms2.metrics",
    "src.ms2.models",
    "src.ms2.models.rnn",
    "src.ms2.models.transformer",
    "src.ms2.training",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.5",
]
